apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: screenfetch
spec:
  version: { { .TagName } }
  homepage: https://github.com/kubernetes-lab/kubectl-screenfetch
  shortDescription: Screenfetch for Kubernetes
  description: |
    This plugin fetchs stats info within a Kubernetes cluster.
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
        {{addURIAndSha "https://github.com/ahmetb/kubectl-screenfetch/releases/download/{{ .TagName }}/kubectl-screenfetch_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
        bin: kubectl-screenfetch
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/ahmetb/kubectl-screenfetch/releases/download/{{ .TagName }}/kubectl-screenfetch_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
      bin: kubectl-screenfetch
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/ahmetb/kubectl-screenfetch/releases/download/{{ .TagName }}/kubectl-screenfetch_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
      bin: kubectl-screenfetch.exe